eclipse/microprofile-metrics

NOTICE
spec/metrics_spec.adoc

This is the original 0002-Metrics proposal from the
evolution repo, but converted to AsciiDoc format.

Original proposal, converted to AsciiDoc.

---

spec/metrics_spec.adoc

Added the required and optional base metrics to the spec doc. I left out the calculated base metrics and servlet metrics.

Adding required and optional base metrics

---

README.adoc

Provide a README

---

spec/metrics_spec.adoc

Add Prometheus format and reorder sections accordingly.

---

spec/metrics_spec.adoc

Config clarification.

---

.editorconfig

Add Editorconfig file from microprofile-config.

---

spec/metrics_spec.adoc

Kept the current content as-is.

Re-organized the metrics specification layout.

---

.gitignore
tck/rest/how_to_run_tests.adoc
tck/rest/pom.xml
tck/rest/src/test/java/org/eclipse/microprofile/metrics/test/MpMetricsIT.java
tck/rest/src/test/resources/base_metrics.xml

Vendor metadata tests are currently commented out. We need to find a strategy for vendor specifc TCK-tests going forward.

Start of a Rest-Test-Kit

---

README.adoc
api/bnd.bnd
api/pom.xml
api/src/main/java/org/eclipse/microprofile/metrics/Counter.java
api/src/main/java/org/eclipse/microprofile/metrics/Counting.java
api/src/main/java/org/eclipse/microprofile/metrics/Gauge.java
api/src/main/java/org/eclipse/microprofile/metrics/Histogram.java
api/src/main/java/org/eclipse/microprofile/metrics/Metadata.java
api/src/main/java/org/eclipse/microprofile/metrics/Meter.java
api/src/main/java/org/eclipse/microprofile/metrics/Metered.java
api/src/main/java/org/eclipse/microprofile/metrics/Metric.java
api/src/main/java/org/eclipse/microprofile/metrics/MetricFilter.java
api/src/main/java/org/eclipse/microprofile/metrics/MetricRegistry.java
api/src/main/java/org/eclipse/microprofile/metrics/MetricType.java
api/src/main/java/org/eclipse/microprofile/metrics/MetricUnit.java
api/src/main/java/org/eclipse/microprofile/metrics/MpMType.java
api/src/main/java/org/eclipse/microprofile/metrics/MpMUnit.java
api/src/main/java/org/eclipse/microprofile/metrics/Sampling.java
api/src/main/java/org/eclipse/microprofile/metrics/Snapshot.java
api/src/main/java/org/eclipse/microprofile/metrics/Timer.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Counted.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Gauge.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Metered.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Metric.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/RegistryType.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Timed.java
pom.xml
spec/metrics_spec.adoc

**Do not accept pull request yet**
Tentative Java API with annotations for discussion purposes.
Still need to:

Add Java API for MicroProfile Metrics

---

spec/src/main/asciidoc/metrics_spec.adoc

Let asciidoctor do the section numbering

---

pom.xml
tck/rest/pom.xml

Smallish cleanup and add the submodules to the parent pom.

Small pom updates/cleanup

---

spec/src/main/asciidoc/metrics_spec.adoc

Start of describing the Java API

---

api/src/main/java/org/eclipse/microprofile/metrics/MetricUnit.java

as they are implementation details. Fixes #38.

Remove scale and base/scale related methods,

---

spec/src/main/asciidoc/metrics_spec.adoc
tck/rest/src/test/java/org/eclipse/microprofile/metrics/test/MpMetricsIT.java
tck/rest/src/test/resources/base_metrics.xml

Clean up names of base metrics. 

---

spec/src/main/asciidoc/metrics_spec.adoc

Adding description of annotations and metric registry

---

spec/src/main/asciidoc/metrics_spec.adoc

Adding missing import statements to annotated name example

---

api/src/main/java/org/eclipse/microprofile/metrics/MetricType.java
spec/src/main/asciidoc/metrics_spec.adoc

@raymondlam This may duplicate/clash a bit with your latest changes. Can you please review?

Clarify the annotations a bit.

---

api/pom.xml

Fixes API pom.xml to point to correct version. Fixes #51

---

spec/src/main/asciidoc/metrics_spec.adoc

remove jmx bridge from spec - fixes #66

---

spec/src/main/asciidoc/metrics_spec.adoc

Clarifying the REST endpoints. Fixes #58, fixes #70, fixes #74.

---

spec/src/main/asciidoc/metrics_spec.adoc

Clarifies the behaviour of how to handle OPTIONS requests. Fixes #81.

---

spec/src/main/asciidoc/metrics_spec.adoc

Add an example of MetricRegistryFactory to the spec. Fixes #83

---

spec/src/main/asciidoc/metrics_spec.adoc

Clarifies the handling of units section of the spec

---

api/src/main/java/org/eclipse/microprofile/metrics/Counter.java
api/src/main/java/org/eclipse/microprofile/metrics/Counting.java
api/src/main/java/org/eclipse/microprofile/metrics/Gauge.java
api/src/main/java/org/eclipse/microprofile/metrics/Histogram.java
api/src/main/java/org/eclipse/microprofile/metrics/Metadata.java
api/src/main/java/org/eclipse/microprofile/metrics/Meter.java
api/src/main/java/org/eclipse/microprofile/metrics/Metered.java
api/src/main/java/org/eclipse/microprofile/metrics/Metric.java
api/src/main/java/org/eclipse/microprofile/metrics/MetricFilter.java
api/src/main/java/org/eclipse/microprofile/metrics/MetricRegistry.java
api/src/main/java/org/eclipse/microprofile/metrics/MetricType.java
api/src/main/java/org/eclipse/microprofile/metrics/MetricUnit.java
api/src/main/java/org/eclipse/microprofile/metrics/Sampling.java
api/src/main/java/org/eclipse/microprofile/metrics/Snapshot.java
api/src/main/java/org/eclipse/microprofile/metrics/Timer.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Counted.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Gauge.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Metered.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Metric.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/RegistryType.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Timed.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/package-info.java
api/src/main/java/org/eclipse/microprofile/metrics/package-info.java

Fix #87 
Signed-off-by: fmhwong <fmhwong@ca.ibm.com>

Use standard MicroProfile copyright header

---

api/src/main/java/org/eclipse/microprofile/metrics/Metadata.java
api/src/main/java/org/eclipse/microprofile/metrics/MetricRegistry.java
api/src/main/java/org/eclipse/microprofile/metrics/MetricType.java
api/src/main/java/org/eclipse/microprofile/metrics/MetricUnit.java
api/src/main/java/org/eclipse/microprofile/metrics/Timer.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Counted.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Gauge.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Metered.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Metric.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/RegistryType.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Timed.java
spec/src/main/asciidoc/metrics_spec.adoc

Updating javadocs in API classes. Fixes #86.

---

spec/src/main/asciidoc/metrics_spec.adoc

Explained how @Metric is used with Methods and Parameters

---

spec/src/main/asciidoc/metrics_spec.adoc

update the types of certain BaseMetrics according to issue #102

---

api/src/main/java/org/eclipse/microprofile/metrics/annotation/Gauge.java
spec/src/main/asciidoc/metrics_spec.adoc

Removing Field Target for @Gauge, it is not supported by metrics-cdi :(

---

api/src/main/java/org/eclipse/microprofile/metrics/MetricUnits.java

update javadoc on MetricUnits.  Fixes #119

---

spec/src/main/asciidoc/metrics_spec.adoc

Remove reference to RHQ metric units. 

---

NOTICE
spec/src/main/asciidoc/metrics_spec.adoc
spec/src/main/resources/META-INF/NOTICE

Adding missing authors to NOTICE files and spec. Fixes #125

---

pom.xml

update pom to add more excludes for RAT - fixes #52

---

spec/src/main/asciidoc/metrics_spec.adoc

Some rewordings and other editorial changes.

---

tck/rest/src/main/resources/base_metrics.xml

Remove optional base metrics from TCK 'required' list

---

tck/api/src/main/java/io/astefanutti/metrics/cdi/se/MeterInjectionBeanTest.java
tck/api/src/main/java/io/astefanutti/metrics/cdi/se/MeteredMethodBean1.java
tck/api/src/main/java/io/astefanutti/metrics/cdi/se/MeteredMethodBean2.java
tck/api/src/main/java/io/astefanutti/metrics/cdi/se/MeteredMethodBeanTest.java
tck/api/src/main/java/io/astefanutti/metrics/cdi/se/TimedMethodBean1.java
tck/api/src/main/java/io/astefanutti/metrics/cdi/se/TimedMethodBean2.java
tck/api/src/main/java/io/astefanutti/metrics/cdi/se/TimedMethodBean3.java
tck/api/src/main/java/io/astefanutti/metrics/cdi/se/TimedMethodBeanLookupTest.java
tck/api/src/main/java/io/astefanutti/metrics/cdi/se/TimedMethodBeanTest.java
tck/api/src/main/java/io/astefanutti/metrics/cdi/se/TimerInjectionBeanTest.java

update TCK to use separate bean copies for each test.  Fixes #138

---

tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java

Servers may have vendor metrics already.

---

api/pom.xml
pom.xml
spec/pom.xml
tck/api/pom.xml
tck/rest/pom.xml

Bump development version

---

tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java

Flipped for loop logic to fix REST TCK

---

tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/HistogramTest.java

Fixing incorrect Histogram Test

---

tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MetricAppBean.java
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java

Test some of the more complex scenarios.
Numbering continues after #163 

Test prometheus metric names and units

---

api/pom.xml
pom.xml
spec/pom.xml
spec/src/main/asciidoc/metrics_spec.adoc
tck/api/pom.xml
tck/rest/pom.xml

Use new release process

---

pom.xml

Fix: revmark -> revremark

---

tck/api/pom.xml

Remove the dependency on the wlp-arq container.

---

spec/src/main/asciidoc/metrics_spec.adoc
tck/rest/pom.xml
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MetricAppBean.java
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java

Adresses #165 
cc @Emily-Jiang @johnament

Describe that the tags need to be supplied via MP-Config.

---

spec/src/main/asciidoc/metrics_spec.adoc

Move the note about returning a 406 for OPTIONS to a better place.

---

api/src/main/java/org/eclipse/microprofile/metrics/Metadata.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Counted.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Metered.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Timed.java
spec/src/main/asciidoc/metrics_spec.adoc
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MetricAppBean2.java
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MicroprofileMetricsTest2.java

Describe reusable metrics. Adresses #162

---

tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java

Check if we got data from the server to prevent a possible NPE

---

tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/ReusableMetricsTest.java

Add the setup() code from MpMetricTest.
Rename the class to end with 'Test' so that surefire picks it up
cc @raymondlam @donbourne

Add setup() and rename so that surefire recognizes the class

---

tck/api/src/main/java/io/astefanutti/metrics/cdi/se/MetricProducerFieldBeanTest.java

Temporarily addresses #188
cc @mkouba @antoinesd @raymondlam @donbourne

Disable the ProducerFieldBeanTest as semantics wrt CDI are unclear.

---

spec/src/main/asciidoc/metrics_spec.adoc

Fixing @Metric description in the table of section 5.3. Fixes #200.

---

spec/src/main/asciidoc/metrics_spec.adoc

Mention `reusable` flag in changelog.

---

spec/src/main/asciidoc/metrics_spec.adoc

Clarify the semantics of the monotonic flag a bit.

---

site.yaml

Signed-off-by: Mike Croft <backtotheoldhouse@gmail.com>

Added first site.yaml based on config

---

spec/pom.xml

$ ls target/generated-docs/
microprofile-metrics-spec-1.1-SNAPSHOT.html	microprofile-metrics-spec-1.1-SNAPSHOT.pdf

add version to rendered spec file name

---

tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/ReusableMetricsTest.java

Changing Java assertions to JUnit assertions

---

api/src/main/java/org/eclipse/microprofile/metrics/annotation/package-info.java
api/src/main/java/org/eclipse/microprofile/metrics/package-info.java

Adding descriptions to package-info.java

---

tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MetricAppBean2.java
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/ReusableMetricsTest.java

Removing testBadReusable and testBadReusable2. Fixes #224

---

api/src/main/java/org/eclipse/microprofile/metrics/DefaultMetadata.java
api/src/main/java/org/eclipse/microprofile/metrics/Metadata.java
api/src/main/java/org/eclipse/microprofile/metrics/MetadataBuilder.java
tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/TagsTest.java
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MetricAppBean.java
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MetricAppBean2.java

Ref: https://github.com/eclipse/microprofile-metrics/issues/228

Should the Metadata be an immutable class? and others improvements

---

api/src/main/java/org/eclipse/microprofile/metrics/annotation/Metric.java
spec/src/main/asciidoc/changelog.adoc

First step in addressing #188.
I checked the spec, it should be ok on how it is correctly worded.

Removing incorrect @InterceptorBinding for @Metric

---

api/src/main/java/org/eclipse/microprofile/metrics/MetricRegistry.java
spec/src/main/asciidoc/changelog.adoc
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MetricAppBean.java

Remove deprecated method. Fixes #268

---

api/src/main/java/org/eclipse/microprofile/metrics/DefaultMetadata.java

Add toString() to DefaultMetadata

---

spec/src/main/asciidoc/app-programming-model.adoc
spec/src/main/asciidoc/changelog.adoc

Mention immutable Metadata and MetadataBuilder, which was introduced in #231.
Fixes #228

Mention immutable Metadata and MetadataBuilder

---

spec/src/main/asciidoc/architecture.adoc
spec/src/main/asciidoc/rest-endpoints.adoc
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java

Switch to OpenMetrics

---

tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java

Separator is now a _ and not a :

---

spec/src/main/asciidoc/architecture.adoc
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java

Better describe and test accept header matching

---

tck/api/pom.xml

remove arquillian-wlp-managed-8.5 dependency in tck/api/pom.xml

---

tck/api/src/main/java/io/astefanutti/metrics/cdi/se/MetricProducerFieldBeanTest.java
tck/api/src/main/java/io/astefanutti/metrics/cdi/se/MetricProducerMethodBeanTest.java
tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/MeterTest.java
tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/TimerTest.java

Address issue #196
Cherry Picked
#194
#191 / #195
And w.r.t #188 
cherry-picked #198

Update TCKs for 1.0.2

---

api/pom.xml
pom.xml
spec/pom.xml
tck/api/pom.xml
tck/rest/pom.xml

Increased version of pom.xml files to 1.0.2-SNAPSHOT

---

api/pom.xml
pom.xml
spec/pom.xml
tck/api/pom.xml
tck/rest/pom.xml

This reverts commit ac2214b4a35b045d834d7413e04d75f771e83ab6.

Revert "[maven-release-plugin] prepare release"

---

tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java

Some @Test and @RunAsClient annotations seem to be missing. I tried adding the annotations and running the tests with SmallRye, they passed for me.

add some apparently forgotten annotations in tests

---

tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MetricAppBean.java
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java
tck/rest/src/main/resources/application_metrics.xml

Signed-off-by: ERIK Kredatus <erik.kredatus@ibm.com>

Added tck test for appending custom String metrics unit to name

---

spec/src/main/asciidoc/required-metrics.adoc

https://github.com/eclipse/microprofile-metrics/issues/323

[#323] update JVM metrics to use tags; some formatting fixes

---

api/src/main/java/org/eclipse/microprofile/metrics/MetadataBuilder.java

Fix failing checkstyle

---

tck/api/src/main/java/io/astefanutti/metrics/cdi/se/ConcurrentGaugeFunctionalBean.java
tck/api/src/main/java/io/astefanutti/metrics/cdi/se/ConcurrentGaugeFunctionalTest.java
tck/api/src/main/java/io/astefanutti/metrics/cdi/se/util/BeanWithControlledInvocation.java
tck/api/src/main/java/io/astefanutti/metrics/cdi/se/util/ControlledInvocation.java
tck/api/src/main/java/io/astefanutti/metrics/cdi/se/util/TimeUtil.java

Hard to say how to verify this right now, I assume OpenLiberty doesn't have this implemented yet, and SmallRye doesn't have multi-dimensional changes so it won't compile against current master. But I developed this with `SmallRye + new counters implementation` against `Specification + the new counters` and it passed, so I assume we could just merge and if there's a problem then fix it later?

Functional test for concurrent gauges

---

api/src/main/java/org/eclipse/microprofile/metrics/annotation/ConcurrentGauge.java
spec/src/main/asciidoc/appendix.adoc
spec/src/main/asciidoc/rest-endpoints.adoc

https://github.com/eclipse/microprofile-metrics/issues/339
@donbourne  please look

[#339] some pending fixes regarding concurrent gauges

---

tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MetricAppBean.java
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java
tck/rest/src/main/resources/application_metrics.xml

Test coverage for smallrye issue https://github.com/smallrye/smallrye-metrics/issues/38 
PR to master coming after relevant 2.0 changes are merged (they conflict with this a bit)

improve tests to verify that metric metadata is taken into account

---

tck/api/pom.xml
tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/GlobalTagsTest.java

@Channyboy please give it a run

Test for global tags with a custom ConfigSource

---

tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MetricAppBean.java
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MetricAppBean2.java
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java

Add rest test to validate Prometheus output of concurrent gauge

---

spec/src/main/asciidoc/required-metrics.adoc

Fix description of jvm.uptime metric

---

spec/src/main/asciidoc/app-programming-model.adoc
spec/src/main/asciidoc/architecture.adoc
spec/src/main/asciidoc/changelog.adoc
spec/src/main/asciidoc/rest-endpoints.adoc

Update changelog, mark breaking changes, do more x-linking.

---

spec/src/main/asciidoc/appendix.adoc
spec/src/main/asciidoc/changelog.adoc
spec/src/main/asciidoc/rest-endpoints.adoc
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MetricAppBean.java
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java

Remove remaining references to Prometheus. Fixes #368

---

spec/src/main/asciidoc/appendix.adoc
spec/src/main/asciidoc/changelog.adoc
spec/src/main/asciidoc/required-metrics.adoc

Changes to base metric names and types

---

tck/running_the_tck.asciidoc

Update TCK readme for 2.0

---

tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java
tck/running_the_tck.asciidoc

Option to skip base tests

---

spec/src/main/asciidoc/appendix.adoc
spec/src/main/asciidoc/architecture.adoc
spec/src/main/asciidoc/rest-endpoints.adoc

minor spec updates

---

spec/src/main/asciidoc/changelog.adoc

Changed the level of one item in the change list, it is not related to OpenMetrics output so it should be one level higher

Fix the changelog formatting a bit

---

.gitignore
api/pom.xml
api/src/main/java/org/eclipse/microprofile/metrics/annotation/package-info.java
api/src/main/java/org/eclipse/microprofile/metrics/package-info.java

Signed-off-by: Emily Jiang <emijiang@uk.ibm.com>

#381 mandate the api versions

---

api/pom.xml
api/src/main/java/org/eclipse/microprofile/metrics/annotation/package-info.java
api/src/main/java/org/eclipse/microprofile/metrics/package-info.java

Also improve Javadoc for package-info files.

Back out plugin updates from PR#381.

---

spec/src/main/asciidoc/app-programming-model.adoc
spec/src/main/asciidoc/changelog.adoc

Add a note about metric registry thread safety. Fixes #300

---

spec/src/main/asciidoc/app-programming-model.adoc

fix MetadataBuilder example

---

tck/api/src/main/java/io/astefanutti/metrics/cdi/se/MultipleMetricsMethodBean.java
tck/api/src/main/java/io/astefanutti/metrics/cdi/se/MultipleMetricsMethodBeanTest.java

See https://github.com/eclipse/microprofile-metrics/issues/404

Make sure TCKs respect that gauges are numbers. Fixes #404

---

spec/src/main/asciidoc/changelog.adoc
tck/rest/pom.xml

upgrade to restassured 4.0.0

---

api/src/main/java/org/eclipse/microprofile/metrics/MetadataBuilder.java

Introduce MetadataBuilder.reusable(boolean). Fixes #407

---

pom.xml

Fix the build on JDK 12. Fixes #409

---

api/src/main/java/org/eclipse/microprofile/metrics/MetricID.java
api/src/main/java/org/eclipse/microprofile/metrics/Tag.java

Performance improvements of metrics creation.

---

api/pom.xml
spec/src/main/asciidoc/changelog.adoc
tck/api/pom.xml
tck/rest/pom.xml

https://github.com/eclipse/microprofile-metrics/issues/417

Exclude javax.el-api from the build. Fixes #417

---

spec/src/main/asciidoc/app-programming-model.adoc
spec/src/main/asciidoc/changelog.adoc

https://github.com/eclipse/microprofile-metrics/issues/399

Text about programmatic registration of metrics. Fixes #399

---

tck/api/src/main/java/io/astefanutti/metrics/cdi/se/ApplicationScopedTimedMethodBean.java
tck/api/src/main/java/io/astefanutti/metrics/cdi/se/MetricProducerFieldBean.java
tck/api/src/main/java/io/astefanutti/metrics/cdi/se/MetricProducerMethodBean.java
tck/api/src/main/java/io/astefanutti/metrics/cdi/se/MultipleMetricsMethodBean.java
tck/api/src/main/java/io/astefanutti/metrics/cdi/se/TimedClassBean.java
tck/api/src/main/java/io/astefanutti/metrics/cdi/se/TimedClassBeanTest.java

https://github.com/eclipse/microprofile-metrics/issues/424

Override toString() where necessary. Fixes #424

---

api/src/main/java/org/eclipse/microprofile/metrics/annotation/package-info.java
api/src/main/java/org/eclipse/microprofile/metrics/package-info.java
tck/running_the_tck.asciidoc

https://github.com/eclipse/microprofile-metrics/issues/422

Update 2.0 references to 2.1

---

api/pom.xml
pom.xml
spec/pom.xml
tck/api/pom.xml
tck/rest/pom.xml

I also created a 2.1.x branch from the current master today. Let's update the version to 2.2.0 for now, if we later find out we need a major version bump, we can update it to 3.0.0

Update master to 2.2.0-SNAPSHOT

---

tck/api/pom.xml

This is for 2.0.x branch
see [#443]

[#443] Fix divergent dependency on hamcrest-integration

---

api/src/main/java/org/eclipse/microprofile/metrics/MetricType.java

Forward-port of https://github.com/eclipse/microprofile-metrics/pull/436 to master for consistency

Small optimization of MetricType retrieval

---

api/pom.xml
pom.xml
spec/pom.xml
tck/api/pom.xml
tck/rest/pom.xml

https://github.com/eclipse/microprofile-metrics/issues/459

Change versioning scheme to two numbers

---

spec/src/main/asciidoc/changelog.adoc
spec/src/main/asciidoc/required-metrics.adoc
tck/rest/src/main/resources/base_metrics.xml

Backporting the fix for #454 to 2.1.x

Update base_metrics.xml to include processCpuLoad and processCpuTime

---

api/src/main/java/org/eclipse/microprofile/metrics/MetadataBuilder.java
spec/src/main/asciidoc/changelog.adoc

Add withOptional* methods to MetadataBuilder

---

api/src/main/java/org/eclipse/microprofile/metrics/MetricID.java
spec/src/main/asciidoc/changelog.adoc

Introduce MetricID.getTagsAsArray()

---

api/pom.xml

Signed-off-by: Emily Jiang <emijiang6@googlemail.com>

#472 enable semantic versioning plugin

---

spec/src/main/asciidoc/changelog.adoc
spec/src/main/asciidoc/required-metrics.adoc
tck/rest/src/main/resources/base_metrics.xml

Add cpu.processCpuTime to 2.2

---

api/pom.xml
pom.xml
spec/pom.xml
tck/api/pom.xml
tck/rest/pom.xml

Update to 2.2.1-SNAPSHOT

---

tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/tags/GlobalTagsTest.java

Fix MP Config usage in GlobalTagsTest

---

spec/src/main/asciidoc/changelog.adoc
tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/MetricIDTest.java
tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/metrics/ConcurrentGaugeFunctionalTest.java
tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/metrics/ConcurrentGaugeTest.java

Signed-off-by: Gaurav Gupta <gaurav.gupta.jc@gmail.com>

MP Metrics TCK improvement - Use WebArchive for deployment

---

api/pom.xml
pom.xml
tck/api/pom.xml
tck/rest/pom.xml

Move to Jakarta artifacts

---

spec/src/main/asciidoc/app-programming-model.adoc

#492 clarification when Gauge values are recomputed

---

api/src/main/java/org/eclipse/microprofile/metrics/annotation/ConcurrentGauge.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Counted.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Gauge.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Metered.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Metric.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/RegistryType.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Timed.java

Update table description in MP Metrics Javadocs

---

api/pom.xml
pom.xml
tck/api/pom.xml
tck/rest/pom.xml

This reverts commit aa3b7d0f2e1800333d0ee092712a2fee421e7454.

Revert "Move to Jakarta artifacts"

---

spec/src/main/asciidoc/architecture.adoc

Fixes https://github.com/eclipse/microprofile-metrics/issues/453

Clarify reusability a bit

---

spec/src/main/asciidoc/required-metrics.adoc

Clarify Spec regarding asynchronous requests for REST stats

---

spec/src/main/asciidoc/changelog.adoc

reorganize change log to conform with other mp spec change logs/release notes

---

api/src/main/java/org/eclipse/microprofile/metrics/MetricRegistry.java
spec/src/main/asciidoc/changelog.adoc

Add MetricRegistry.getType()

---

tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/MetricRegistryTest.java

and some formatting fixes
Fixes https://github.com/eclipse/microprofile-metrics/issues/540

Add a TCK test for MetricRegistry.getType()

---

tck/optional/src/main/java/org/eclipse/microprofile/metrics/test/optional/MpMetricOptionalTest.java

Assert that 5 seconds passed in async test

---

api/src/main/java/org/eclipse/microprofile/metrics/MetricRegistry.java
spec/src/main/asciidoc/app-programming-model.adoc

Fixes https://github.com/eclipse/microprofile-metrics/issues/549

Clarifications for determining metric names

---

api/src/main/java/org/eclipse/microprofile/metrics/ConcurrentGauge.java
api/src/main/java/org/eclipse/microprofile/metrics/SimpleTimer.java
spec/src/main/asciidoc/architecture.adoc
spec/src/main/asciidoc/changelog.adoc
spec/src/main/asciidoc/required-metrics.adoc
spec/src/main/asciidoc/rest-endpoints.adoc
tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/cdi/SimpleTimerInjectionBeanTest.java
tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/metrics/SimpleTimerFunctionalBean.java
tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/metrics/SimpleTimerFunctionalTest.java
tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/metrics/SimplyTimedMethodBean1.java
tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/metrics/SimplyTimedMethodBean2.java
tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/metrics/SimplyTimedMethodBeanLookupTest.java
tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/metrics/SimplyTimedMethodBeanTest.java
tck/optional/src/main/java/org/eclipse/microprofile/metrics/test/optional/MpMetricOptionalTest.java
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java

Spec + TCK changes to introduce max/min for Simple Timer

---

tck/optional/src/main/java/org/eclipse/microprofile/metrics/test/optional/LambdaMatcher.java
tck/optional/src/main/java/org/eclipse/microprofile/metrics/test/optional/MpMetricOptionalTest.java

Fix flaky MpMetricOptionalTest

---

tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/cdi/MetricProducerMethodBeanTest.java

Fix for appropriate sorted set order

---

spec/src/main/asciidoc/app-programming-model.adoc
spec/src/main/asciidoc/changelog.adoc
tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/MetricRegistryTest.java

Fixes https://github.com/eclipse/microprofile-metrics/issues/234

Specify behavior of registration methods wrt passed metadata

---

tck/rest/pom.xml

In relation to https://github.com/OpenLiberty/open-liberty/issues/11537

Upgrading rest-assured to 4.3.0

---

tck/rest/pom.xml

In relation to https://github.com/OpenLiberty/open-liberty/issues/11537

Upgrade rest-assured to 4.3.0

---

api/src/main/java/org/eclipse/microprofile/metrics/DefaultMetadata.java
api/src/main/java/org/eclipse/microprofile/metrics/Metadata.java
api/src/main/java/org/eclipse/microprofile/metrics/MetadataBuilder.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/ConcurrentGauge.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Counted.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Metered.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/SimplyTimed.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Timed.java
spec/src/main/asciidoc/app-programming-model.adoc
spec/src/main/asciidoc/architecture.adoc
spec/src/main/asciidoc/changelog.adoc
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MetricAppBean2.java
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/ReusedMetricsTest.java

Fixes https://github.com/eclipse/microprofile-metrics/issues/553

Remove the concept of reusability

---

api/pom.xml
pom.xml
spec/pom.xml
tck/api/pom.xml
tck/optional/pom.xml
tck/rest/pom.xml

Change version to 2.3.2-SNAPSHOT

---

tck/optional/pom.xml

In realtion to https://github.com/OpenLiberty/open-liberty/issues/11537

Edit optional tck to use rest-assured 4.3.0

---

spec/src/main/asciidoc/app-programming-model.adoc

Clarify rules for gauge injection

---

spec/src/main/asciidoc/changelog.adoc
spec/src/main/asciidoc/required-metrics.adoc
tck/optional/src/main/java/org/eclipse/microprofile/metrics/test/optional/MetricAppBeanOptional.java
tck/optional/src/main/java/org/eclipse/microprofile/metrics/test/optional/MpMetricOptionalTest.java
tck/optional/src/main/java/org/eclipse/microprofile/metrics/test/optional/MpMetricsArithmeticExceptionMapper.java

Handling of unmapped exceptions for REST metrics

---

api/src/main/java/org/eclipse/microprofile/metrics/annotation/Gauge.java

Remove mention about @Gauge applied on field

---

spec/src/main/asciidoc/required-metrics.adoc
tck/optional/src/main/java/org/eclipse/microprofile/metrics/test/optional/MetricAppBeanOptional.java
tck/optional/src/main/java/org/eclipse/microprofile/metrics/test/optional/MpMetricOptionalTest.java

Remove tests for REST methods with array parameters in the optional TCK

---

spec/src/main/asciidoc/changelog.adoc

Update changelog with the breaking changes to the Metadata Interface

---

pom.xml
tck/api/pom.xml
tck/optional/pom.xml
tck/rest/pom.xml
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MetricAppBean.java
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java

Remove dependency on MP Config

---

api/pom.xml

Signed-off-by: Emily Jiang <emijiang6@googlemail.com>

update baseline to the latest released version

---

.github/ISSUE_TEMPLATE/01-compatible-certification-request.md
api/pom.xml
api/src/main/javadoc/licenses/Draft/license.html
api/src/main/javadoc/licenses/Final/license.html
api/src/main/resources/META-INF/LICENSE
pom.xml
spec/pom.xml
spec/src/main/asciidoc/license-efsl.adoc
spec/src/main/asciidoc/metrics_spec.adoc
tck/api/pom.xml
tck/licenses/Draft/LICENSE
tck/licenses/Final/LICENSE.md
tck/optional/pom.xml
tck/rest/pom.xml

Signed-off-by: Emily Jiang <emijiang6@googlemail.com>

Produce the required artifacts under MPWG

---

tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/MeterTest.java
tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/TestUtils.java
tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/TimerTest.java

Increase tolerance and time for testing rates for Meter and Timer TCK tests

---

api/src/main/java/org/eclipse/microprofile/metrics/annotation/package-info.java

Update package version

---

api/src/main/java/org/eclipse/microprofile/metrics/MetricRegistry.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Counted.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Gauge.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Metric.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/RegistryScope.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/RegistryType.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Timed.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/package-info.java
spec/src/main/asciidoc/app-programming-model.adoc
spec/src/main/asciidoc/appendix.adoc
tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/MetricRegistryTest.java
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java

~For discussion...~
No  test changes in this PR, only made changes to tests where  API has changed.
minimal documentation change in this PR.
Fix #677
Fix #684
~## Since this is based off of the unmerged  https://github.com/eclipse/microprofile-metrics/pull/664~
~## **See the latest commit for the changes relevant to custom scopes: 0a2d3b4386c82340655c77d16f87bfcc5e6c46f3**~

 Provide support for user defined Custom Scopes for Metric Registries

---

api/src/main/java/org/eclipse/microprofile/metrics/MetricRegistry.java

javadoc tweaks for MetricRegistry

---

api/src/main/java/org/eclipse/microprofile/metrics/package-info.java

update packageinfo example for Timers

---

spec/src/main/asciidoc/required-metrics.adoc

Update Required metrics doc to use Prometheus base units

---

api/src/main/java/org/eclipse/microprofile/metrics/Gauge.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Gauge.java

Update Gauges to only accept Number  values

---

spec/src/main/asciidoc/appendix.adoc

New section for alternatives considered and updates to references

---

api/src/main/java/org/eclipse/microprofile/metrics/DefaultMetadata.java
api/src/main/java/org/eclipse/microprofile/metrics/Metadata.java
api/src/main/java/org/eclipse/microprofile/metrics/MetadataBuilder.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Counted.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Gauge.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Metric.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/Timed.java
api/src/main/java/org/eclipse/microprofile/metrics/package-info.java
spec/src/main/asciidoc/app-programming-model.adoc
spec/src/main/asciidoc/appendix.adoc
spec/src/main/asciidoc/architecture.adoc
spec/src/main/asciidoc/required-metrics.adoc
spec/src/main/asciidoc/rest-endpoints.adoc
tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/MetricRegistryTest.java
tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/cdi/stereotype/StereotypeCountedClassBeanTest.java
tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/cdi/stereotype/stereotypes/CountMeWithSpecifiedMetadata.java
tck/rest/src/main/application_metrics.xml
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MetricAppBean.java
tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java
tck/rest/src/main/resources/application_metrics.xml

fixes #704
Will be conflicts if https://github.com/eclipse/microprofile-metrics/pull/718 is merged first.
Will need to rebase then.

Remove displayName from API, TCK, Spec

---

spec/src/main/asciidoc/rest-endpoints.adoc

allow metrics endpoint to be disabled

---

spec/src/main/asciidoc/app-programming-model.adoc
spec/src/main/asciidoc/architecture.adoc
spec/src/main/asciidoc/base-metrics.adoc
spec/src/main/asciidoc/microprofile-metrics-spec.asciidoc

provides the spec updates required for #680

spec updates to make base metrics be optional

---

spec/src/main/asciidoc/appendix.adoc
spec/src/main/asciidoc/changelog.adoc
spec/src/main/asciidoc/microprofile-metrics-spec.asciidoc

Last minute spec items

---

tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/metrics/GaugeMethodBean.java
tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/metrics/GaugeMethodBeanTest.java

Add a test for testing a private method annotated with @Gauge

---

api/pom.xml
pom.xml
tck/README.adoc
tck/api/pom.xml
tck/optional/pom.xml
tck/pom.xml
tck/rest/pom.xml

Update and fix dependencies to use deps from parent pom/boms + update TCK README

---

api/src/main/java/org/eclipse/microprofile/metrics/annotation/Timed.java
api/src/main/java/org/eclipse/microprofile/metrics/annotation/package-info.java
api/src/main/java/org/eclipse/microprofile/metrics/package-info.java

Default is nanoseconds as per docs

---

api/src/main/java/org/eclipse/microprofile/metrics/annotation/RegistryScope.java
spec/src/main/asciidoc/appendix.adoc
spec/src/main/asciidoc/changelog.adoc

Update RegistryScope to be qualifer

---

api/pom.xml
pom.xml
tck/api/pom.xml
tck/optional/pom.xml
tck/rest/pom.xml

Remove some unnecessary dependencies

Remove the unnecessary dependencies
