- spec/metrics_spec.adoc
Update the base metrics to use camel case with dot hierarchy. Reordered the instance variable %s in accordance to typical naming conventions. Lastly, clarified why there maybe multiple garbage collector instances.
> Update base metrics

- spec/metrics_spec.adoc
> Make enum for units consistent. 

- spec/metrics_spec.adoc
> Fix the metadata example to use fooVal consistently.

- spec/metrics_spec.adoc
Return Metadata as a JSON object rather than a JSON Array
> Update format of returned Metadata

- api/src/main/java/org/eclipse/microprofile/metrics/Metadata.java
- api/src/main/java/org/eclipse/microprofile/metrics/MetricUnit.java
- api/src/main/java/org/eclipse/microprofile/metrics/annotation/Counted.java
- api/src/main/java/org/eclipse/microprofile/metrics/annotation/Gauge.java
- api/src/main/java/org/eclipse/microprofile/metrics/annotation/Metered.java
- api/src/main/java/org/eclipse/microprofile/metrics/annotation/Metric.java
- api/src/main/java/org/eclipse/microprofile/metrics/annotation/Timed.java
- spec/src/main/asciidoc/metrics_spec.adoc
Fixes #67, fixes #56, fixes #54, fixes #50, and fixes #44.
> Switching MetricUnits to use String instead of Enum.

- spec/src/main/asciidoc/metrics_spec.adoc
> remove reference to using field annotation for Gauge.  Fixes #116

- tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java
Some implementations (like the WF-Swarm fraction I am working on) already have the target application deployed when the tests start and thus have already registered the metrics coming from annotated entities.
So like for vendor we need to check that if application metrics are exposed, that the map is not empty.
Likewise if application data is present, the return code is 200 and not 204.
> It is possible to have application metrics at this point.

- tck/api/pom.xml
- tck/rest/pom.xml
Occurs if you run mvn for the first time (when the parent artifact does not already exist) due to the folder locations of the tck modules.
> Fixed parent pom path location for tcks

- tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java
- tck/rest/src/main/resources/application_metrics.xml
Like for the base metrics, check the application metrics (that are coming from annotations) for their name , unit and type.
> Allow to test application metadata for unit and type

- tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MetricAppBean.java
- tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java
Make sure that tags on application level Metrics are propagated to the output.
Could potentially test more, but I did not want to pollute the `MetricAppBean` too much with it.
> Test application level tags

- api/src/main/java/org/eclipse/microprofile/metrics/MetricRegistry.java
Do not merge until discussion. For 1.1.
register(String,Metric,Metadata) has a redundant String name in the parameter which is already provided in the Metadata.
> Adding register(Metadata,Metric) and deprecating register(String,Metric,Metadata)

- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/MeterTest.java
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/TimerTest.java
Addresses #160 and #190
I think we should disable them until we have better tests that also work on Windows or on slow computers.
cc @fmhwong @donbourne 
> Disable brittle tests.

- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/TimerTest.java
Add on to #191. Should be re-enabled when #193 gets resolved.
> Comment out timerRate references since the test was disabled

- tck/api/src/main/java/io/astefanutti/metrics/cdi/se/MetricProducerFieldBeanTest.java
- tck/api/src/main/java/io/astefanutti/metrics/cdi/se/MetricProducerMethodBeanTest.java
Fixes #187 
Added `@Inject private MetricProducerFieldBean bean` for MetricProducerFieldBeanTest.java to be safe. The metrics were injected in `incrementCountersFromInjection` (test sequence 3) but are referenced since the first test.
> Calls a method on the MetricProducerMethodBean to instantiate it.

- spec/src/main/asciidoc/metrics_spec.adoc
- tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MetricAppBean.java
- tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java
Technically Prometheus also allows a colon, but as Brian says that this should not show up in a name, I am translating that as well.
> Clarify metric name rules for Prometheus output and add tests

- api/src/main/java/org/eclipse/microprofile/metrics/Metadata.java
The whole point is to make the name's field a required field in Metadata class and also avoid an NPE in the hashcode method.
Ps: Once we cannot change the metrics values when it's seted, we, in the future, might discuss to make this class immutable and create it using a builder pattern.
E.g:
`MetaData metadata = MetaData.builder().withName("name").withDisplayName("name").build();`
> Make the field name mandatory in the MetaData class

- api/src/main/java/org/eclipse/microprofile/metrics/Counter.java
- api/src/main/java/org/eclipse/microprofile/metrics/Histogram.java
- api/src/main/java/org/eclipse/microprofile/metrics/Meter.java
- api/src/main/java/org/eclipse/microprofile/metrics/MetricFilter.java
- api/src/main/java/org/eclipse/microprofile/metrics/Timer.java
> * Every method declaration in the body of an interface is implicitly public (§6.6).
> * Every method declaration in the body of an interface is implicitly abstract, so its body is always represented by a semicolon, not a block.
> * It is permitted, but discouraged as a matter of style, to redundantly specify the public and/or abstract modifier for a method declared in an interface.
> 
https://docs.oracle.com/javase/specs/jls/se7/html/jls-9.html#jls-9.4
> Remove redundant public in the interface

- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/HistogramTest.java
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/MeterTest.java
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/TestUtils.java
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/TimerTest.java
- tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MetricAppBean.java
- tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java
Modified Meter/Timer rate tests to be less implementation dependent. I've set the tolerance to a very generous +/- 2.5% which should cover slow running machines.
Fixes #225 - Histogram
Fixes #160 - Meter/Timer
Fixes #190 - Meter/Timer
> Added a tolerance to Histogram, Meter and Timer tests results

- api/src/main/java/org/eclipse/microprofile/metrics/MetadataBuilder.java
This is an alternative approach to #249, as #249 is still a bit problematic ( see comments)
On top (and this is worse), the strict check will make a larger number of tests fail. See e.g. https://github.com/eclipse/microprofile-metrics/blob/master/tck/api/src/main/java/io/astefanutti/metrics/cdi/se/GaugeMethodBean.java#L28 where a Gauge has a unit of `NONE`, which would trigger an IAE.
We need to sort this out and then also adapt tests.
> Skip unit-for-type checking. This needs more work.

- api/src/main/java/org/eclipse/microprofile/metrics/DefaultMetadata.java
Making this public allows implementations to extend it.
> Make DefaultMetadata public. Fixes #252

- api/bnd.bnd
We would [like to use microprofile-metrics in Eclipse SmartHome](https://www.eclipse.org/forums/index.php?t=msg&th=1094339&goto=1793459&#msg_1793459) as well and trying to add it, I had to noticed that the manifest declares mandatory dependencies to `javax`packages, which are not part of JavaSE.
While these dependencies might be relevant at compile time of the project, I absolutely do not see any need for their presence at runtime; only the implementations might have those dependencies, but that should be left to them.
I'd therefore suggest to mark those dependencies as optional, which let's people easily use this API on a plain JavaSE as well.
Signed-off-by: Kai Kreuzer <kai@openhab.org>
> Make enterprise dependencies optional, so that it can be used on SE as well

- tck/api/src/main/java/io/astefanutti/metrics/cdi/se/CountedClassBean.java
- tck/api/src/main/java/io/astefanutti/metrics/cdi/se/CountedClassBeanTest.java
- tck/api/src/main/java/io/astefanutti/metrics/cdi/se/CountedMethodBean.java
- tck/api/src/main/java/io/astefanutti/metrics/cdi/se/CountedMethodBeanTest.java
- tck/api/src/main/java/io/astefanutti/metrics/cdi/se/MonotonicCountedMethodBeanTest.java
Remove usage of word 'monotonic' from counter tests because all counters are now monotonic
Also makes CounterBeanMethod test a bit easier to troubleshoot - the uncaught exception in the auxiliary thread is currently getting discarded and will not be shown anywhere in the test log, with this commit it should be seen. (yes, exactly this happened to me when implementing SmallRye 2.0)
> Remove usage of word 'monotonic' from counter tests

- tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java
- tck/rest/src/main/resources/base_metrics.xml
For 2.0, we renamed the JVM metric `gc.%s.count` to `gc.count{name=%s}` and `gc.%s.time` to `gc.time{name=%s}` (via https://github.com/eclipse/microprofile-metrics/commit/a4902b1768cbcbef04124ee1d5b8a1c24e62f264). This should be verified in a TCK test. We can't assert particular Garbage collector names that will be present at runtime, but I guess we can reasonably expect that at least one `gc.count` and one `gc.time` metric will exist, and we can check that they contain a `name` tag (but we don't check its actual value).
> [#343] test for checking the gc.count and gc.time metrics

- spec/src/main/asciidoc/changelog.adoc
- spec/src/main/asciidoc/rest-endpoints.adoc
- tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MetricAppBean.java
- tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java
- tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/ReusableMetricsTest.java
- JSON format in GET requests append tags in
metricName;tag=value;tag=value format
- Metrics with sub-resources have the tags appended to the leaf element
(i.e metricName.subresource;tag=value)
Addresses Issue #331 
> Modified spec + TCK to better accomodate multidimensional metrics in JSON format

- spec/src/main/asciidoc/rest-endpoints.adoc
@Channyboy 
@pilhuhn 
@donbourne
> Missing _current in examples of TYPE and HELP lines of concurrent gauge

- spec/src/main/asciidoc/changelog.adoc
- spec/src/main/asciidoc/rest-endpoints.adoc
- tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java
formatting.  Camel case is no longer automatically converted to snake
case. The TCK is updated to reflect this.
Fixes #357 
> Modify the specification regarding translation rules for OpenMetrics

- spec/src/main/asciidoc/required-metrics.adoc
Some JVMs like substrate do not have full flavoured JMX stats. Add a comment on what should happen in this case.
> Note on base metrics for JVMs that can't provide them.

- api/src/main/java/org/eclipse/microprofile/metrics/MetricID.java
- spec/src/main/asciidoc/architecture.adoc
- spec/src/main/asciidoc/changelog.adoc
Necessary spec additions to support distinguishing metrics from different applications in a single application server.
While designing this change, I did a crude PoC implementation of this in WildFly to make sure that it's possible to do there: https://github.com/jmartisk/wildfly/commits/master-mp-app-name-proof-of-concept (includes a test)
@Channyboy @pilhuhn @donbourne please review
> Application labels

- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/GlobalTagsTest.java
- tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java
- tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/ReusableMetricsTest.java
For the vendors that might _always_ provide the `_app` tag via `mp.metric.appname` config. The TCK may fail for them.
This PR updates to the TCK tests so that it will _ignore_ the '_app' tag.
Excuse the copy and paste for each test :(
In a managed environment , it needs to run _as the client_ to resolve all the RestAssured and Hamcrest classes.
Sticking a `@RunAsClient` on a private method doesn't seem to work.
> Modify TCK so that it will preprocess the "_app" tag out if it is present

- tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java
- tck/rest/src/main/resources/base_metrics.xml
As per April 23rd discussion
```
gc.%s.count                                 // .count -> .total
classloader.totalLoadedClass.count          // .count -> .total (loadedClasses.total)
classloader.totalUnloadedClass.count        // .count -> .total (unloadedClasses.total)
thread.count                                // Counter -> Gauge
thread.daemon.count                         // Counter -> Gauge
classloader.currentLoadedClass.count        // Counter -> Gauge
thread.max.count                            // Counter -> Gauge? (leave counters for use as accumulating counts)
```
Spec update followed up by @donbourne 
> Modified TCK to satisfy metric name/type updates

- spec/src/main/asciidoc/changelog.adoc
- spec/src/main/asciidoc/metrics_spec.adoc
> Move changelog to end of spec.

- tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java
- tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/ReusableMetricsTest.java
The TCK may have appnames/context-roots with dashes.
e.g `2d3cb509-7843-4628-9c4e-6fb5921e366d`
> Need to add a dash in regex for the TCK's appname

- .gitignore
- tck/rest/pom.xml
- tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java
- tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/ReusableMetricsTest.java
Signed-off-by: Felix Wong <fmhwong@ca.ibm.com>
Fixes #391 
Version 3.0.0 of `io.rest-assured` has the `ClassCastException` fixed.
> Update rest-assured to 3.0.0

- api/src/main/java/org/eclipse/microprofile/metrics/Gauge.java
- api/src/main/java/org/eclipse/microprofile/metrics/annotation/Gauge.java
- spec/src/main/asciidoc/changelog.adoc
#304 
While this is technically a breaking change, this only can break code that was using non-numeric gauges, which is something that would probably not work anyway for different reasons. So I think we could get this into 2.1.
> Clarify that gauges are numbers. Fixes #304

- spec/src/main/asciidoc/changelog.adoc
- spec/src/main/asciidoc/rest-endpoints.adoc
- tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java
https://github.com/eclipse/microprofile-metrics/issues/264
> Allow empty or omitted 'vendor' scope in JSON export. Fixes #264

- spec/src/main/asciidoc/changelog.adoc
I forgot to update the changelog, follows up on https://github.com/eclipse/microprofile-metrics/pull/411
> Update changelog wrt MetadataBuilder.reusable(boolean)

- api/pom.xml
- pom.xml
- spec/pom.xml
- tck/api/pom.xml
- tck/rest/pom.xml
Seems that after releasing 2.0.1 we didn't set the development version to `2.0.2-SNAPSHOT`
> Move version to 2.0.2-SNAPSHOT

- tck/rest/pom.xml
Upgrading to shrinkwrap 2.2.4 still pulls in org.jsoup:jsoup:1.7.2 as well as the latest shrinkwrap package set at 3.1.1
```
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ microprofile-metrics-rest-tck ---
[INFO] org.eclipse.microprofile.metrics:microprofile-metrics-rest-tck:jar:2.1-SNAPSHOT
[INFO] \- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-impl-maven:jar:3.1.1:compile
[INFO]    \- org.apache.maven.wagon:wagon-http-lightweight:jar:2.12:compile
[INFO]       \- org.apache.maven.wagon:wagon-http-shared:jar:2.12:compile
[INFO]          \- org.jsoup:jsoup:jar:1.7.2:compile
```
```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ microprofile-metrics-rest-tck ---
[INFO] org.eclipse.microprofile.metrics:microprofile-metrics-rest-tck:jar:2.1-SNAPSHOT …
```
> Upgraded TCK dependencies

- tck/api/src/main/java/io/astefanutti/metrics/cdi/se/TimedMethodBeanTest.java
https://github.com/eclipse/microprofile-metrics/issues/430
Backport to 2.0.x
> Remove TimedMethodBeanTest.callSelfInvocationTimedMethodOnce

- api/src/main/java/org/eclipse/microprofile/metrics/MetricType.java
A simple change to reuse static instance of `EnumSet<MetricType>` instead a creating it in `MetricType.from()` methods.
> Small optimization of MetricType retrieval

- spec/src/main/asciidoc/changelog.adoc
- spec/src/main/asciidoc/required-metrics.adoc
> Update spec to include Process CPU Time

- spec/src/main/asciidoc/changelog.adoc
- tck/rest/src/main/resources/base_metrics.xml
> Update base_metrics.xml to include processcputime

- spec/src/main/asciidoc/changelog.adoc
- spec/src/main/asciidoc/required-metrics.adoc
- tck/rest/src/main/resources/base_metrics.xml
Backporting the fix for #454 to 2.0.x
> Update base_metrics.xml to include processCpuTime and processCpuLoad

- api/src/main/java/org/eclipse/microprofile/metrics/ConcurrentGauge.java
- api/src/main/java/org/eclipse/microprofile/metrics/MetricType.java
- api/src/main/java/org/eclipse/microprofile/metrics/MetricUnits.java
- spec/src/main/asciidoc/changelog.adoc
#455 
While at this, I noticed some classes that use 2 spaces for indentation while most other classes use 4. So I reformatted them.
> Introduce MetricType.fromClassName, plus reformat some classes. 

- api/pom.xml
- api/src/main/java/org/eclipse/microprofile/metrics/Gauge.java
- api/src/main/java/org/eclipse/microprofile/metrics/annotation/Gauge.java
- pom.xml
- spec/pom.xml
- spec/src/main/asciidoc/changelog.adoc
- tck/api/pom.xml
- tck/rest/pom.xml
2.2 release = 2.1.0 + revert of the problematic change with gauges
After we decide to indeed go this way and merge this, master will need to be updated to target 2.3-SNAPSHOT
This also fixes the problem that we had three numbers in 2.1.0 release version, so this turns it into 2.2 (two numbers)
Things that went into 2.1.x branch after the 2.1.0 release will later be copied over to 2.2.x branch and released as 2.2.1.
@donbourne @Emily-Jiang @OndroMih please have a look
> Preparations for 2.2 release

- api/pom.xml
- api/src/main/java/org/eclipse/microprofile/metrics/Gauge.java
- api/src/main/java/org/eclipse/microprofile/metrics/annotation/Gauge.java
- api/src/main/java/org/eclipse/microprofile/metrics/annotation/package-info.java
- api/src/main/java/org/eclipse/microprofile/metrics/package-info.java
- pom.xml
- spec/pom.xml
- spec/src/main/asciidoc/changelog.adoc
- tck/api/pom.xml
- tck/rest/pom.xml
- update to `2.3-SNAPSHOT`
- enable baseline plugin, for now against 2.0
- revert the problematic change to gauges
- update version in `package-info.java` files
Don't merge until we actually release 2.2 from the contents of `2.2.x` branch
> Update master to 2.3

- pom.xml
After infrastructure upgrades we're encountering jenkin build failures.
Due to :
```
[INFO] [INFO] --- maven-gpg-plugin:1.6:sign (sign-artifacts) @ microprofile-metrics-parent ---
[INFO] gpg: signing failed: Not a tty
[INFO] gpg: signing failed: Not a tty
[INFO] [INFO] -------------------------
```
See for example: https://ci.eclipse.org/microprofile/view/Release/job/MicroProfile%20Releases/283/console
The main microprofile umbrella project is able to pass their jenkins build by specying the pinentry mode to loopback
See:
https://github.com/eclipse/microprofile/blob/8228cb5e7430f44e6a58b569775a3316e4a5844f/pom.xml#L316-L321
> Address gpg signing failurs with jenkins build

- api/src/main/java/org/eclipse/microprofile/metrics/SimpleTimer.java
> Update SimpleTimer to use java.time.Duration for update() and getElapsedTime()

- spec/src/main/asciidoc/appendix.adoc
- spec/src/main/asciidoc/architecture.adoc
- spec/src/main/asciidoc/changelog.adoc
- spec/src/main/asciidoc/required-metrics.adoc
Current mpConfig key is `mp.metrics.enable.restful.stats`
or could use `mp.metrics.collect.restful.stats`?
or any other suggestions else?
> Introduce optional base metrics from RESTful stats

- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/MetricIDTest.java
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/metrics/ConcurrentGaugeTest.java
Replace calls to `addAsManifestResource` by `addAsWebInfResource` as
deployments are now WebArchives.
Signed-off-by: Jeff Mesnil <jmesnil@gmail.com>
> MP Metrics TCK improvement - Use WebArchive for deployment

- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/metrics/ConcurrentGaugedClassBeanTest.java
backport of https://github.com/eclipse/microprofile-metrics/pull/538 to 2.3.x
> Correct MetricID computation in ConcurrentGaugedClassBeanTest

- spec/src/main/asciidoc/app-programming-model.adoc
- spec/src/main/asciidoc/changelog.adoc
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/cdi/stereotype/StereotypeCountedClassBean.java
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/cdi/stereotype/StereotypeCountedClassBeanTest.java
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/cdi/stereotype/StereotypeCountedClassBeanWithSpecifiedMetadata.java
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/cdi/stereotype/stereotypes/CountMe.java
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/cdi/stereotype/stereotypes/CountMeWithSpecifiedMetadata.java
> Specify handling of CDI stereotypes with metrics

- api/src/main/java/org/eclipse/microprofile/metrics/MetricUnits.java
- spec/src/main/asciidoc/rest-endpoints.adoc
Some corrections for inconsistencies in the specification:
* `MEGABITS` are 1000 `KILOBITS`
* tags are given in alphabetical order in all examples for REST API
* JSON format uniformly uses no space before the `:` and a space after the colon of a object member
* OpenMetrics `TYPE` is only given once for each OpenMetrics name in the example(s)
Secondly I added patterns to each metric type for JSON and OpenMetrics format that explains in a different way how the overall OpenMetrics name is composed or how the data is made into a JSON tree and member names.
> Some corrections for spec inconsistencies and REST data patterns

- api/src/main/java/org/eclipse/microprofile/metrics/DefaultMetadata.java
- api/src/main/java/org/eclipse/microprofile/metrics/Metadata.java
- api/src/main/java/org/eclipse/microprofile/metrics/MetadataBuilder.java
- spec/src/main/asciidoc/changelog.adoc
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/cdi/stereotype/StereotypeCountedClassBeanTest.java
This is a suggestion to make `Metadata` more predictable when it comes to difference between values being `null` (not present) and set to their defaults explicitly.
`Metadata` methods returning _plain_ `String` or `MetricType` never return `null`, 
* display name defaults to name, 
* unit defaults to `MetricUnits.NONE` 
* description defaults to `""` 
* type defaults to `MetricType.INVALID`
This default is always applied in last possible moment when getter reads the field value.
Until then any value including `null` may be passed to builder `with`-methods. `null` simple makes values not present and triggers the defaults unless the value is accessed via one of the `Optional`-returning methods which give access to the underlying value in the sense that they allow to distinguish between a …
> More straight forward and uniform optionals for Metadata

- spec/src/main/asciidoc/architecture.adoc
The current description in the spec indicates that apps should handle population of the _app tag automatically based on the context root of the web app to which the metric belongs.  In practice we're not aware of anyone who has implemented this, and it may give the impression by the presence in the spec that this is typical of app servers.  Removing this makes the official way to set the _app tag be just through MP Config.
Also removed the paragraph telling multi-app server vendors that there should be a single MetricRegistry instance shared between all apps.  In practice multi-app server vendors have successfully implemented this in both per-app registries and by using one registry for all app's metrics.  So this guidance seems unnecessary.
> Remove text about deriving _app tag from context root

- api/src/main/java/org/eclipse/microprofile/metrics/MetricRegistry.java
- spec/src/main/asciidoc/changelog.adoc
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/metrics/GaugeTest.java
See #592 
Was going to add the below methods without tag parameters but would cause ambiguity issues.
```
1. <T> Gauge<T> gauge(String name, Supplier<T> supplier);
2. <T> Gauge<T> gauge(Metadata metadata, Supplier<T> supplier);
3. <T> Gauge<Long> gauge(String name, T object, ToDoubleFunction<T> func;
4. <T> Gauge<Long> gauge(Metadata metadata, T object, ToDoubleFunction<T> func;
```
For example, wanting to calling `gauge("name", supplier, null)` is ambiguous with **3**
and similarily calling `gauge(metadata, supplier, null)` is ambigious with **4**
> Remove existing MetricRegistry's retrieve/register gauge() methods and introduce new ones that make use of Functions

- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/metrics/MeterTest.java
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/metrics/TimerTest.java
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/util/TestUtils.java
Double the time.
Increase tolerance from 2.5% to 15%.
#619
> Increase tolerance and time for testing rates for Meter and Timer TCK tests

- tck/rest/pom.xml
With Java 16, the TCKs will encounter issues when using the rest assured library. 
e.g.
```
org.eclipse.microprofile.metrics.test.MpMetricTest:java.lang.ExceptionInInitializerError: null
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
at java.base/java.lang.reflect.AccessibleObject.setAccessible(AccessibleObject.java:130)
at org.codehaus.groovy.reflection.CachedClass$3$1.run(CachedClass.java:86)
```
See : https://github.com/OpenLiberty/open-liberty/issues/16162
This PR upgrades the rest-assured dependency to address these test failures.
> Upgrade REST assured dependency to address Java 16 TCK failures

- spec/src/main/asciidoc/app-programming-model.adoc
- spec/src/main/asciidoc/architecture.adoc
- spec/src/main/asciidoc/changelog.adoc
- spec/src/main/asciidoc/intro.adoc
- spec/src/main/asciidoc/rest-endpoints.adoc
- removed references to `@ConcurrentGauge`
- removed references to `@SimplyTimed`
- removed references to `@Metered`
---
- removed references to MetricRegisty.concurrentGauge
- removed references to MetricRegistry.simpleTimer
- removed references to MetricRegistry.meter
---
- removed references to MetricRegistry.register methods allowing Metric implementations to be registered
- removed reference to CDI extension from Dropwizard as potential implementation
---
- added custom scopes / custom MetricRegistrys
- changed metrics/base to metrics?scope=base
- changed metrics/vendor to metrics?scope=vendor
- changed metrics/application to metrics?scope=application
- added requirement that scope be added to all metrics as a tag
---
- added …
> initial spec updates for MP Metrics 5.0

- spec/src/main/asciidoc/architecture.adoc
- spec/src/main/asciidoc/rest-endpoints.adoc
fixes #678 
- full update of prometheus text based exposition format output section
- removes details that may vary across implementations
- includes details about how to map from Gauge, Counter, Timer, Histogram to the prometheus format
> Spec prom output

- spec/src/main/asciidoc/architecture.adoc
> block use of _scope and _app tag names by apps

- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/metrics/DefaultNameMetricMethodBeanTest.java
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/metrics/MultipleMetricsMethodBeanTest.java
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/tags/CounterFieldTagBean.java
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/tags/CounterFieldTagBeanTest.java
- tck/rest/src/main/application_metrics.xml
- tck/rest/src/main/resources/application_metrics.xml
- Ensure metrics that use the same name x tag combination are exactly
the same (i.e. can't have metrics with same name where one uses tags and
the other does not, or that all tag keys used are exactly the same
- remove references remaining references to removed metrics meter (i.e.
meter)
Fixes #714 
May cause conflicts if https://github.com/eclipse/microprofile-metrics/pull/716 is merged first.
Will need to rebase then.
>  Clean up any small problems in TCK

- api/src/main/java/org/eclipse/microprofile/metrics/Snapshot.java
- spec/src/main/asciidoc/rest-endpoints.adoc
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/metrics/HistogramFieldBeanTest.java
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/metrics/HistogramTest.java
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/metrics/TimerTest.java
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/tags/HistogramTagFieldBeanTest.java
Update Snapshot used by Histogram and Timer
- Removed getMedian, getXXXPercentile, getMin, getStdDev, getValues from Snapshot
- Added inner static class PercentileValue to Snapshot, percentileValues() method to Snapshot
- Spec updates
- TCK updates
^methods removed were those that can not be supported by micrometer
fixes #695
fixes #696
> Update Histogram/Timer's Snapshot

- spec/src/main/asciidoc/app-programming-model.adoc
- spec/src/main/asciidoc/architecture.adoc
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/MetricIDTest.java
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/MetricRegistryTest.java
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/tags/TagsTest.java
> Update SPEC and TCK; IllegalArgumentException when metrics using the same name do not have the same tag names

- spec/src/main/asciidoc/architecture.adoc
- spec/src/main/asciidoc/rest-endpoints.adoc
- tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java
- tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/ReusedMetricsTest.java
Depends on the following to be merged first.
https://github.com/eclipse/microprofile-metrics/pull/707
*^This PR is based off of this as it needs to change text that was added in #707
and
https://github.com/eclipse/microprofile-metrics/pull/709
Depends on #709 first before TCKs can be updated.
DRAFT as there still requires changed in TCK.
Fixes #705 
(^branch erroneously named as 700 )
REST TCKs in #709 are more explicit in checking Prometheus output in that there are more tests now.
Those tests check for the previous `scope`/`_scope` tag which will now be changed to `mp_scope`.
> Change from _app and _scope to mp_app and mp_scope

- spec/src/main/asciidoc/micrometer-backends.adoc
- spec/src/main/asciidoc/microprofile-metrics-spec.asciidoc
This PR is for issue #671 
This PR contains additional text for the specification documentation around the use of Micrometer Registries, other than the standard Prometheus pull via the `/metrics` endpoint.
Specifically, this PR attempts to call out:
* Implementing with Micrometer is optional
* Supporting alternative Micrometer Backends/Registries is also optional
* If a vendor wishes to support these registries, recommendations are made around discovery (via the classpath), and configuration to ensure the configuration is consistent with Micrometer itself, and consistent with MicroProfile through the use of the MicroProfile config specification.
I've included an example of these recommendations for an implementation as a CDI extension, using a Producer to add Registries.
Signed-off-by: …
> Recommendations for Micrometer Backends

- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/tags/TagsTest.java
not comprehensive test of all api and annotation calls
Fixes #738
> add tests that check for IAE when using a an illegal tag name

- api/pom.xml
- pom.xml
- tck/api/pom.xml
- tck/optional/pom.xml
- tck/rest/pom.xml
Also update the Metrics TCK poms to pull in MicroProfile Parent TCK BOM
Also filled in properties and dependencies in pom.xml that were removed from MicroProfile Parent.
Fixes #747
> Update MicroProfile Metrics Parent to MicroProfile Parent 3.0

- api/src/main/java/org/eclipse/microprofile/metrics/MetricRegistry.java
- api/src/main/java/org/eclipse/microprofile/metrics/annotation/RegistryType.java
- api/src/main/java/org/eclipse/microprofile/metrics/annotation/package-info.java
- spec/src/main/asciidoc/app-programming-model.adoc
- spec/src/main/asciidoc/appendix.adoc
- spec/src/main/asciidoc/changelog.adoc
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/MetricRegistryTest.java
Fixes #746
Up for discussion during MP Metrics call.
> Add RegistryType and MetricRegistry.Type back in, but deprecated. Upate API, Spec, TCK

- tck/README.adoc
Related to #752
MP Metrics 5 is dependent on JEE 10 which is Java 11 only.
> Update maven-compiler-plugin configuration to reference java 11

- api/pom.xml
- pom.xml
- tck/README.adoc
- tck/api/pom.xml
- tck/optional/pom.xml
- tck/pom.xml
- tck/rest/pom.xml
Related to : https://github.com/eclipse/microprofile-metrics/issues/752
This PR removes the Jakarta EE 10.0.0 core API dependency in exchange to use the explicit Jakarta EE dependencies needed for MicroProfile Metrics (TCK/API).
In general, MP Metrics relies on `CDI` and `Restful WS`.
Exclusions were used in the MP Metrics `pom.xml`s similar to that of the Jakarta EE 10.0.0 core API  ( i.e. `jakarta.jakartaee-core-api`)at https://repo1.maven.org/maven2/jakarta/platform/jakarta.jakartaee-core-api/10.0.0/jakarta.jakartaee-core-api-10.0.0.pom where _all_ dependencies are excluded and only the dependencies that are _*needed*_ by MP Metrics is is defined in the `pom.xml` (i.e. `jakarta.interceptor-api` and `jakarta.inject-api` ). This creates the lightest foot print for MP Metrics. …
> Explicitly set dependency for Jakarata EE technologies used by MP Metrics

- api/src/main/java/org/eclipse/microprofile/metrics/annotation/Counted.java
- api/src/main/java/org/eclipse/microprofile/metrics/annotation/Gauge.java
- api/src/main/java/org/eclipse/microprofile/metrics/annotation/Metric.java
- api/src/main/java/org/eclipse/microprofile/metrics/annotation/RegistryScope.java
- api/src/main/java/org/eclipse/microprofile/metrics/annotation/Timed.java
These were found while trying to generate MicroProfile 6.0 javadocs. The html was still produced, but some of the links did not work. The code changes will fix the links by changing the syntax in comments for what the javadoc command generates.
`@link MetricRegistry.APPLICATION_SCOPE` for instance generates just text:
This is fixed by changing it to ``@link MetricRegistry#APPLICATION_SCOPE` which generates a link:
> Fixed 10 javadoc errors with MicroProfile 6.0

- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/metrics/GaugeMethodBean.java
- tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/metrics/GaugeMethodBeanTest.java
Fixes #769 
Private gauges should not be mandated by the TCK.
It is up to the vendor whether they want to support private gauges or not.
> Remove private gauges from TCK

- spec/src/main/asciidoc/app-programming-model.adoc
Resolves #767
1. Mentions parameters explicitly in introducing the first naming convention table.
2. Adds a footnote in that table urging developers to always use `@Metric` with `name` on any injected metric parameter.
Signed-off-by: tim.quinn@oracle.com <tim.quinn@oracle.com>
> Clarify naming convention for injected parameters

- spec/src/main/asciidoc/architecture.adoc
- spec/src/main/asciidoc/changelog.adoc
> Update multi-app section to recommend usage of `mp.metrics.defaultAppName`

- tck/optional/src/main/java/org/eclipse/microprofile/metrics/test/optional/MPMetricBaseMetricsTest.java
- tck/optional/src/main/java/org/eclipse/microprofile/metrics/test/optional/MetricAppBeanOptional.java
The `toString()` method is not needed in cases the underlying method handles the conversion. Also calling toString() on a String is redundant. Removing them simplifies the code.
* UnnecessaryToStringCall (3)
> Refactor bad smell UnnecessaryToStringCall

- api/src/main/java/org/eclipse/microprofile/metrics/Snapshot.java
- tck/rest/src/main/java/org/eclipse/microprofile/metrics/test/MpMetricTest.java
> Fix doclint errors

- api/pom.xml
- api/src/main/java/org/eclipse/microprofile/metrics/Snapshot.java
- pom.xml
This is to fix the issue #796 by providing an implementation to the abstract method and also skip this change from semantic versioning check.
> Address the issue #796

- api/pom.xml
Additional change for #796 
The plug-in seems to be needed at build-time for the annotation added to the code, but there is no need for it--and it should not be--in the runtime path and in the runtime paths of artifacts that depend on this component.
> Exclude plug-in from runtime path
